### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by Alan01** [linuxmint/blueman#10]
Now that you have forked Blueman, will you pull (updated) translations from Weblate?

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by clefebvre** [comment]
No, this is only a github fork, not a project fork. We'll catch up with blueman by re-fetching master.
