### ISSUE TITLE
Regression: icon does not appear under 5.15 kernel

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/blueman#11]
blueman: blueman/vanessa,now 2.3.1+mint1+vanessa amd64 [installed]
BlueZ: bluez/jammy,now 5.64-0ubuntu1 amd64 [installed]
Distribution: Mint 21
Desktop environment: Cinnamon

EDITED.

* [X] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

Upon boot, sometimes I have a bluetooth applet and sometimes I do not. I have `blueman-applet` set to run at startup; bluetooth does seem enabled. Upon a boot after which there is no applet, if I run `blueman-applet` in a terminal, then I see the following.

```
blueman-applet 17.47.19 WARNING  PluginManager:151 __load_plugin: Not loading PPPSupport because its conflict has higher priority
blueman-applet 17.47.19 WARNING  PluginManager:151 __load_plugin: Not loading DhcpClient because its conflict has higher priority
```
I did not have the problem on Mint 20.3.

**Comment by LinuxOnTheDesktop** [comment]
Here is the promised further information, from my machine when running the 5.15 kernel.

The troubleshooting document says: 'To retrieve useful information, the best starting point is to run blueman-applet --loglevel debug from a Terminal window. It needs to be shut down, since only one instance may be running. You should always be able to do that with killall blueman-applet.' 'It needs to be shut down' - what, _before_ running `blueman-applet --loglevel debug`? I will try that. Results are [here on PasteBin](https://pastebin.com/zQdUwrBh) (and the paste will expire after a year).

The same document says: 'The blueman-report tool is a simple helper to log blueman output. It also provides a way to comment on the steps you take while creating the log and uploads the commented log file.' So, should I, actually, run that tool, rather than `blueman-applet --loglevel debug`?

**Comment by LinuxOnTheDesktop** [comment]
Strangley, I find now that, after a reboot, the applet does not start even on the _5.18_ kernel.

**Comment by clefebvre** [comment]
@LinuxOnTheDesktop please report directly to blueman upstream. This isn't a fork per se, it's just our packaged version of Blueman.

https://github.com/blueman-project/blueman
