### ISSUE TITLE
Cannot connect headsets

### ISSUE THREAD

**Issue by svprdga** [linuxmint/blueman#12]
blueman: 2.3.4+mint1+vanessa
BlueZ: 5.64-0ubuntu1
Distribution: Linux Mint 21 Cinnamon
Desktop environment: Cinnamon 5.4.12+vanessa

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

I can't connect my headset via bluetooth to my computer. It was working well a couple of weeks ago, today I updated blueman to `2.3.4+mint1+vanessa` but it still doesn't work.

In the following log I have tried to connect it, the UI said 'ok' but no real connection was made.

Log: https://pastebin.com/DS2uyzM0

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by cschramm** [comment]
What do you mean with "the UI said 'ok'"?

(glad to see 2.3.4 is in Mint now :relieved:)

**Comment by svprdga** [comment]
The notification that confirms that the connection has been established appears (sorry, don't remember the exact words). Other times that I tried another error appeared in the bottom part of the screen: 'connection reset by local' (or similar).

**Comment by cschramm** [comment]
Three seconds after you triggered a connection (I cannot tell for which device), an iPhone shows up as connected. Coincidence, user mistake, or some severe misdirection in blueman?

**Comment by svprdga** [comment]
> Three seconds after you triggered a connection (I cannot tell for which device), an iPhone shows up as connected. Coincidence, user mistake, or some severe misdirection in blueman?

I have an iPhone, but it was turned off and I have never connect it to this machine... 

Note: while taking those logs, I performed a search and an iPhone appeared there (as well as other smartphones, TVs, computers).

**Comment by svprdga** [comment]
First I tried with the _pair_ option, but it didn't work:

```
  % blueman-manager                                                                         !1505
blueman-manager 09.29.30 WARNING  ManagerDeviceList:396 _monitor_power_levels: Failed to get power levels, probably a LE device.
blueman-manager 09.29.30 WARNING  ManagerDeviceList:396 _monitor_power_levels: Failed to get power levels, probably a LE device.
blueman-manager 09.30.37 ERROR    Manager:223 error_handler: org.freedesktop.DBus.Error.UnknownObject Method "Pair" with signature "" on interface "org.bluez.Device1" doesn't exist
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/blueman/bluez/Base.py", line 78, in callback
    value = proxy.call_finish(result).unpack()
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownObject: Method "Pair" with signature "" on interface "org.bluez.Device1" doesn't exist
 (41)
```

The I tried with the _connect_ option and it finally worked. After that I have disconnected the headset and try to reconnect it, a notification appeared then to ask if I accepted the connection.

So, I could finally connect the headset...

**Comment by cschramm** [comment]
That's weird. The `Pair` method and the `Connect` method that we use are part of the same interface. It's not possible that one exists but the other does not.

**Comment by svprdga** [comment]
Yeah, it's pretty weird. At the moment it's still working so I'm not going to touch anything, feel free to close this thread if you see fit.

Thanks for the help.
