### ISSUE TITLE
Blueman Issues in Linux Mint 21

### ISSUE THREAD

**Issue by kmkom** [linuxmint/blueman#13]
blueman: up to date in Mint 21.1
BlueZ: up to date in Mint 21.1
Distribution: Linux Mint 21.1
Desktop environment: Cinnamon 5.6.5

* [y] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

Blueman doesn't work here at all, I can't connect any of my BT devices with it. It is not because of the Intel AX200/210 card and its driver, because the workaround with bluetoothctl or with [Bluetuith](https://github.com/darkhz/bluetuith) works!
Here are some problem reports from other users in the Linux Mint forum:
[Bluetooth Issues in Linux Mint 21](https://forums.linuxmint.com/viewtopic.php?f=52&t=383393)
[blueman-applet glitch when connected to bluetooth devices](https://forums.linuxmint.com/viewtopic.php?t=378387)

Thanks.

**Comment by cschramm** [comment]
I fail to find a problem statement here.

**Comment by kmkom** [comment]
Who does not read the error descriptions of other Mint users in the Linux Mint forum, briefly:
Blueman typically brings the (red) error message "error: le-connection-abort by local". I can only see that Blueman randomly(?) selects a device from the BT scan environment list and wants to connect to it, but these devices (e.g. sometimes those of my neighbors!) refuse to do so. I have therefore decided to uninstall Blueman and not to continue to annoy my neighbors...
Thanks for reading.

**Comment by clefebvre** [comment]
2.3.5 coming up.
