### ISSUE TITLE
Issues with French translations

### ISSUE THREAD

**Issue by clefebvre** [linuxmint/blueman#2]
- [x] Casing issues. French should not use title case (like it is done in English).
- [x] Some items are not translated (in the applet, Exit, Help, etc..)

**Comment by the-saddest-clown** [comment]
And some items are poorly translated.
Linux Mint 20.3 Xfce
blueman-manager 2.1.2
In the example below :

- In the tooltip box "_A2DP sink_" is roughly translated as "_A2DP poubelle_".

- And the "_Envoyer un pense-bête_" menu item is not clear at all.

![Capture d’écran_2022-04-14_07-32-37](https://user-images.githubusercontent.com/83234199/163320256-3e533f89-3027-48b6-87be-390f3ddd5ab1.png)

**Comment by clefebvre** [comment]
Fixed in Weblate.
